const ACTIONS = {
    LOGIN: 'LOGIN',
    GET_TOKEN: 'GET_TOKEN',
    GET_USER: 'GET_USER',
    GET_PROJECTS: 'GET_PROJECTS',
    SET_ISCHATOPEN: 'SET_ISCHATOPEN',
    SET_UNREAD_ROOM: 'SET_UNREAD_ROOM',
    SET_LAST_MSG: 'SET_LAST_MSG',
    SET_ACTIVE_CHAT: 'SET_ACTIVE_CHAT'
}

export default ACTIONS